export const en = {
  langName: "English",
  nav: {
    home: "Home",
    features: "Features",
    screens: "Screens",
    pricing: "Pricing",
    faq: "FAQs",
    login: "Sign in",
  },
  ticker: [
    "Live • Riverside CC 148/4 (18.2)",
    "4+ camera angles per delivery",
    "Coaching review • frame-by-frame",
    "Request an invite for your club",
    "Scoreboards ready for stream overlay",
  ],
  hero: {
    l1: "Every ball.",
    l2: "Every angle.",
    l3: "Every advantage.",
    body: "CricLume turns a club match into a full record: ball-by-ball scoring, synced phone cameras at every angle, live scoreboards and a coaching review room the whole squad can learn from.",
    ctaPrimary: "Sign in to CricLume",
    ctaSecondary: "See the screens",
    liveNow: "Live now",
  },
  stats: [
    { k: "4+", v: "camera angles per ball" },
    { k: "<1s", v: "to log a delivery" },
    { k: "100%", v: "match history kept" },
  ],
  home: {
    matchDayKicker: "Match day",
    matchDayTitle: "Built for match day",
    allFeatures: "All features",
    fixturesKicker: "Fixtures",
    fixturesTitle: "Upcoming matches",
    scoring: "Scoring",
    vs: "vs",
    seasonKicker: "Season",
    seasonTitle: "Club standings",
    standingsNote: "Standings, run rates and player records build themselves from every ball you score.",
    tablePos: "Pos",
    tableClub: "Club",
    tableP: "P",
    tableW: "W",
    tablePts: "Pts",
    ctaKicker: "Review room",
    ctaTitle1: "Watch the match back,",
    ctaTitle2: "ball by ball",
    ctaBody: "Every delivery links to its own synced angles — slow it down, step frames, draw on it and send voice notes to the squad before the next session.",
    ctaButton: "Get access",
    trustKicker: "Built with",
    trustTitle: "Clubs, leagues and academies",
    tags: { league: "League", academy: "Academy", cup: "T20 Cup" },
  },
  features: [
    {
      title: "Fast ball-by-ball scoring",
      body: "Runs, dots, wides, no-balls, byes, leg-byes, penalties and every dismissal type — with undo and timestamps on every delivery.",
    },
    {
      title: "Multi-phone camera room",
      body: "Pair phones at both ends and side-on — or add as many angles as the situation needs. One tap starts the room, angles stay linked to the ball they captured.",
    },
    {
      title: "Coaching review",
      body: "Slow motion, frame stepping, angle switching, zoom, drawing tools and voice notes for post-match feedback.",
    },
    {
      title: "Live scoreboards",
      body: "Broadcast-quality scoreboards with run rate, partnerships, fall of wickets and a rolling delivery timeline.",
    },
    {
      title: "Desktop and mobile",
      body: "Score from a phone on the boundary or a laptop in the clubhouse — the same match, in sync.",
    },
    {
      title: "Clubs, teams and players",
      body: "Organisations, competitions, teams, players and grounds modelled from the ground up for season-long history.",
    },
    {
      title: "Share live scoring",
      body: "Leagues and clubs choose who watches a match unfold in real time — the opposition club, followers, the league office, or a public link for supporters.",
    },
  ],
  featuresTab: {
    kicker: "Platform",
    title: "Features",
    intro: "Everything that ships in the current CricLume build.",
    watchTitle: "Who can watch live",
    watchBody: "Leagues set a default for a competition, clubs can override it per match — and change it mid-innings.",
    watchOptions: [
      { t: "Club only", d: "Scorers, coaches and members of your own club." },
      { t: "Opposition club", d: "The other team's staff and players follow the same live feed." },
      { t: "League office", d: "Competition admins see every fixture live for results and compliance." },
      { t: "Public link", d: "Supporters and family follow the scoreboard in a browser — no account needed." },
    ],
    alsoTitle: "Also included",
    alsoItems: [
      "Field zones, fielder selection and delivery timeline",
      "Undo on any ball, with a full audit of edits",
      "Voice notes and AI-audit presentation in review",
      "Competitions, innings and deliveries stored per club",
      "Demo match data so you can trial before onboarding",
    ],
  },
  screensTab: {
    kicker: "Product tour",
    title: "Screens",
    intro: "Dashboards, scoreboards, mobile scoring and the review room.",
    items: [
      { label: "Club dashboard", caption: "Desktop • live, upcoming and completed matches with run-rate and wagon-wheel analytics" },
      { label: "Live scoreboard", caption: "Broadcast view • score, batters, bowlers, over timeline and fall of wickets" },
      { label: "Mobile scoring", caption: "Phone • thumb-first scoring pad with extras, dismissals and recent deliveries" },
      { label: "Coaching review", caption: "Desktop • four synced angles, frame-by-frame scrubbing and drawing tools" },
    ],
  },
  pricing: {
    kicker: "Plans",
    title: "Pricing & subscriptions",
    intro: "Start free with one team. Move to a club or league subscription when you want more angles, longer video retention and competition-wide control.",
    showing: "Showing prices for",
    detecting: "Detecting your region…",
    selectLabel: "Select your country",
    mostPopular: "Most popular",
    free: "Free",
    custom: "Custom",
    plans: [
      {
        name: "Starter",
        period: "one team",
        blurb: "Get a side scoring properly and sharing a live scoreboard.",
        perks: [
          "Ball-by-ball scoring for 1 team",
          "Live scoreboard + public match link",
          "No camera room — upgrade to add angles",
          "Basic batting & bowling stats",
          "Light advertising on scoreboard and review pages",
        ],
        cta: "Start free",
      },
      {
        name: "Club",
        period: "per team / month",
        blurb: "The full match-day kit for clubs running several sides.",
        perks: [
          "Unlimited teams and fixtures",
          "Unlimited camera angles per delivery",
          "90-day video retention + clip export",
          "Coaching review with slow-motion tagging",
          "Share live scoring with opposition clubs",
          "Season-long club analytics",
        ],
        cta: "Request an invite",
      },
      {
        name: "League",
        period: "per competition / season",
        blurb: "Competition-wide scoring, standings and governance.",
        perks: [
          "Every club in the competition included",
          "League standings, results and admin console",
          "Default visibility rules across fixtures",
          "12-month video retention",
          "Sponsor branding on live streams",
          "Data export and priority support",
        ],
        cta: "Talk to us",
      },
    ],
    revenueKicker: "Business model",
    revenueTitle: "How CricLume makes money",
    revenue: [
      { title: "Subscriptions", body: "Recurring club and league plans are the core of the business — billed monthly or annually per team, with two months free on annual." },
      { title: "Video & storage add-ons", body: "Extra retention, 4K clips and bulk season archives are priced on top of the base tier." },
      { title: "Sponsorship & streams", body: "Leagues can sell branded overlays and sponsored public match links; CricLume takes a share of the placement." },
      { title: "Services", body: "Onboarding, historic data migration and bespoke reporting for larger leagues and academies." },
    ],
    footnote: "Annual billing saves two months on every paid tier. Schools and junior sections get 50% off the Club plan.",
  },
  faq: {
    kicker: "Answers",
    title: "FAQs",
    items: [
      { q: "Who is CricLume for?", a: "Clubs, leagues, schools and academies that want proper ball-by-ball records and video they can actually coach from — without a broadcast budget." },
      { q: "Do I need special cameras?", a: "No. The camera room pairs ordinary phones. Start with one at each end and one side-on, then add as many extra angles as you need — every recording is tied back to the delivery it captured." },
      { q: "Can I score without signal?", a: "Scoring is built to keep working through patchy ground coverage and sync back up when the connection returns." },
      { q: "Does it handle rain rules?", a: "Yes. CricLume applies standard rain rules to adjust targets and results when a match is interrupted." },
      { q: "Where is video stored?", a: "Clips and annotations are stored against the match in your organisation's own space, with consent and privacy controls part of the launch roadmap." },
      { q: "Can other clubs and the league watch our scoring live?", a: "Yes. Each match has a visibility setting: private to your club, shared with the opposition club, open to your league, or a public link anyone can follow. Leagues can also set a default for every fixture in a competition." },
      { q: "How does CricLume make money?", a: "Clubs and leagues pay an annual subscription per team or competition, billed on the tier that matches how much scoring, video and analysis they use. Extra video storage, league-wide packages and sponsor-branded streams are paid add-ons." },
      { q: "Is there a free option?", a: "Yes. Starter is free for a single team with ball-by-ball scoring and a live scoreboard. The camera room is not included — you add angles once you move to the Club plan. It is supported by light advertising on scoreboard and review pages." },
      { q: "How do I get access?", a: "Sign in if your club already has an account, or request an invite and we will get your club set up." },
    ],
  },
  login: {
    badge: "Gated access",
    title: "Sign in",
    body: "Sign in to open the scoring platform, or request an invite for your club.",
    email: "Club email",
    password: "Password",
    submit: "Enter the platform",
    sent: "Thanks — we have logged your request and will be in touch.",
    noAccount: "No account yet?",
    requestInvite: "Request an invite for your club.",
    copyright: "CricLume. See every ball. Shape every game.",
  },
  footer: {
    desc: "Ball-by-ball scoring, multi-angle camera rooms, live scoreboards and coaching review for clubs, leagues and academies.",
    explore: "Explore",
    access: "Access",
    accessLine1: "By invitation for clubs",
    accessLine2: "Request access for your team",
    cta: "Request an invite",
    copyright: "CricLume — See every ball. Shape every game.",
    legal: "CricLume is a trading name of iTechLounge Ltd.",
  },
  backToHome: "Back to home",
};

export type Content = typeof en;

export const de: Content = {
  langName: "Deutsch",
  nav: { home: "Start", features: "Funktionen", screens: "Ansichten", pricing: "Preise", faq: "FAQ", login: "Anmelden" },
  ticker: [
    "Live • Riverside CC 148/4 (18.2)",
    "4+ Kamerawinkel pro Ball",
    "Trainingsanalyse • Bild für Bild",
    "Einladung für deinen Club anfragen",
    "Anzeigetafeln bereit für Stream-Overlay",
  ],
  hero: {
    l1: "Jeder Ball.",
    l2: "Jeder Winkel.",
    l3: "Jeder Vorteil.",
    body: "CricLume macht aus einem Clubspiel eine vollständige Aufzeichnung: Scoring Ball für Ball, synchronisierte Handykameras aus jedem Winkel, Live-Anzeigetafeln und ein Analyseraum, aus dem das ganze Team lernt.",
    ctaPrimary: "Bei CricLume anmelden",
    ctaSecondary: "Ansichten entdecken",
    liveNow: "Jetzt live",
  },
  stats: [
    { k: "4+", v: "Kamerawinkel pro Ball" },
    { k: "<1s", v: "um einen Ball zu erfassen" },
    { k: "100%", v: "Spielhistorie gespeichert" },
  ],
  home: {
    matchDayKicker: "Spieltag",
    matchDayTitle: "Für den Spieltag gebaut",
    allFeatures: "Alle Funktionen",
    fixturesKicker: "Spielplan",
    fixturesTitle: "Kommende Spiele",
    scoring: "Scoring",
    vs: "gegen",
    seasonKicker: "Saison",
    seasonTitle: "Tabelle",
    standingsNote: "Tabellen, Run Rates und Spielerstatistiken entstehen automatisch aus jedem erfassten Ball.",
    tablePos: "Pl.",
    tableClub: "Club",
    tableP: "Sp",
    tableW: "S",
    tablePts: "Pkt",
    ctaKicker: "Analyseraum",
    ctaTitle1: "Sieh das Spiel erneut,",
    ctaTitle2: "Ball für Ball",
    ctaBody: "Jeder Ball ist mit seinen synchronisierten Winkeln verknüpft — verlangsamen, Bild für Bild springen, einzeichnen und Sprachnotizen ans Team schicken.",
    ctaButton: "Zugang erhalten",
    trustKicker: "Entwickelt mit",
    trustTitle: "Clubs, Ligen und Akademien",
    tags: { league: "Liga", academy: "Akademie", cup: "T20-Pokal" },
  },
  features: [
    { title: "Schnelles Scoring Ball für Ball", body: "Runs, Dots, Wides, No-Balls, Byes, Leg-Byes, Strafen und jede Art von Dismissal — mit Rückgängig-Funktion und Zeitstempel für jeden Ball." },
    { title: "Kameraraum mit mehreren Handys", body: "Handys an beiden Enden und seitlich koppeln — oder so viele Winkel hinzufügen, wie nötig. Ein Tipp startet den Raum, jeder Winkel bleibt mit seinem Ball verknüpft." },
    { title: "Trainingsanalyse", body: "Zeitlupe, Einzelbildschritte, Winkelwechsel, Zoom, Zeichenwerkzeuge und Sprachnotizen für das Feedback nach dem Spiel." },
    { title: "Live-Anzeigetafeln", body: "Anzeigetafeln in Broadcast-Qualität mit Run Rate, Partnerschaften, Wicket-Verlauf und rollender Ball-Timeline." },
    { title: "Desktop und Mobil", body: "Scoring per Handy am Spielfeldrand oder per Laptop im Clubhaus — dasselbe Spiel, synchron." },
    { title: "Clubs, Teams und Spieler", body: "Organisationen, Wettbewerbe, Teams, Spieler und Plätze — von Grund auf für eine ganze Saison modelliert." },
    { title: "Live-Scoring teilen", body: "Ligen und Clubs entscheiden, wer ein Spiel in Echtzeit verfolgt — der Gegner, Fans, die Ligaverwaltung oder ein öffentlicher Link." },
  ],
  featuresTab: {
    kicker: "Plattform",
    title: "Funktionen",
    intro: "Alles, was im aktuellen CricLume-Build enthalten ist.",
    watchTitle: "Wer live zuschauen darf",
    watchBody: "Ligen legen eine Voreinstellung fest, Clubs können sie pro Spiel überschreiben — auch während des Innings.",
    watchOptions: [
      { t: "Nur Club", d: "Scorer, Trainer und Mitglieder des eigenen Clubs." },
      { t: "Gegnerischer Club", d: "Staff und Spieler des anderen Teams sehen denselben Live-Feed." },
      { t: "Ligaverwaltung", d: "Wettbewerbs-Admins sehen jedes Spiel live für Ergebnisse und Compliance." },
      { t: "Öffentlicher Link", d: "Fans und Familie folgen der Anzeigetafel im Browser — ohne Konto." },
    ],
    alsoTitle: "Ebenfalls enthalten",
    alsoItems: [
      "Feldzonen, Fielder-Auswahl und Ball-Timeline",
      "Rückgängig bei jedem Ball, mit vollständiger Änderungshistorie",
      "Sprachnotizen und KI-Auswertung in der Analyse",
      "Wettbewerbe, Innings und Bälle pro Club gespeichert",
      "Demo-Spieldaten zum Testen vor dem Onboarding",
    ],
  },
  screensTab: {
    kicker: "Produkttour",
    title: "Ansichten",
    intro: "Dashboards, Anzeigetafeln, mobiles Scoring und der Analyseraum.",
    items: [
      { label: "Club-Dashboard", caption: "Desktop • laufende, kommende und beendete Spiele mit Run-Rate- und Wagon-Wheel-Analysen" },
      { label: "Live-Anzeigetafel", caption: "Broadcast-Ansicht • Punktestand, Batter, Bowler, Over-Timeline und Wicket-Verlauf" },
      { label: "Mobiles Scoring", caption: "Handy • daumenfreundliches Scoring-Pad mit Extras, Dismissals und letzten Bällen" },
      { label: "Trainingsanalyse", caption: "Desktop • vier synchrone Winkel, Einzelbild-Navigation und Zeichenwerkzeuge" },
    ],
  },
  pricing: {
    kicker: "Tarife",
    title: "Preise & Abos",
    intro: "Starte kostenlos mit einem Team. Wechsle zu einem Club- oder Liga-Abo, wenn du mehr Winkel, längere Videospeicherung und wettbewerbsweite Kontrolle willst.",
    showing: "Preise für",
    detecting: "Region wird erkannt…",
    selectLabel: "Land auswählen",
    mostPopular: "Am beliebtesten",
    free: "Kostenlos",
    custom: "Individuell",
    plans: [
      {
        name: "Starter",
        period: "ein Team",
        blurb: "Bring ein Team ins richtige Scoring und teile eine Live-Anzeigetafel.",
        perks: [
          "Scoring Ball für Ball für 1 Team",
          "Live-Anzeigetafel + öffentlicher Spiel-Link",
          "Kein Kameraraum — Upgrade für Winkel",
          "Basis-Statistiken für Batting & Bowling",
          "Leichte Werbung auf Anzeigetafel- und Analyseseiten",
        ],
        cta: "Kostenlos starten",
      },
      {
        name: "Club",
        period: "pro Team / Monat",
        blurb: "Die komplette Spieltags-Ausrüstung für Clubs mit mehreren Teams.",
        perks: [
          "Unbegrenzte Teams und Spiele",
          "Unbegrenzte Kamerawinkel pro Ball",
          "90 Tage Videospeicherung + Clip-Export",
          "Analyse mit Zeitlupen-Tagging",
          "Live-Scoring mit Gegnern teilen",
          "Club-Analysen für die ganze Saison",
        ],
        cta: "Einladung anfragen",
      },
      {
        name: "Liga",
        period: "pro Wettbewerb / Saison",
        blurb: "Scoring, Tabellen und Verwaltung für den gesamten Wettbewerb.",
        perks: [
          "Alle Clubs des Wettbewerbs enthalten",
          "Ligatabellen, Ergebnisse und Admin-Konsole",
          "Standard-Sichtbarkeitsregeln für alle Spiele",
          "12 Monate Videospeicherung",
          "Sponsoren-Branding auf Live-Streams",
          "Datenexport und Priority-Support",
        ],
        cta: "Kontakt aufnehmen",
      },
    ],
    revenueKicker: "Geschäftsmodell",
    revenueTitle: "Wie CricLume Geld verdient",
    revenue: [
      { title: "Abonnements", body: "Wiederkehrende Club- und Liga-Tarife sind der Kern des Geschäfts — monatlich oder jährlich pro Team, mit zwei Freimonaten bei Jahreszahlung." },
      { title: "Video- & Speicher-Add-ons", body: "Längere Speicherung, 4K-Clips und komplette Saisonarchive werden zusätzlich berechnet." },
      { title: "Sponsoring & Streams", body: "Ligen können gebrandete Overlays und gesponserte Spiel-Links verkaufen; CricLume erhält einen Anteil." },
      { title: "Services", body: "Onboarding, Migration historischer Daten und individuelle Auswertungen für größere Ligen und Akademien." },
    ],
    footnote: "Jahreszahlung spart zwei Monate in jedem bezahlten Tarif. Schulen und Jugendabteilungen erhalten 50 % Rabatt auf den Club-Tarif.",
  },
  faq: {
    kicker: "Antworten",
    title: "FAQ",
    items: [
      { q: "Für wen ist CricLume?", a: "Für Clubs, Ligen, Schulen und Akademien, die saubere Ball-für-Ball-Daten und Videos wollen, mit denen man wirklich trainieren kann — ohne Broadcast-Budget." },
      { q: "Brauche ich spezielle Kameras?", a: "Nein. Der Kameraraum koppelt normale Handys. Starte mit je einem an beiden Enden und einem seitlich und füge beliebig viele Winkel hinzu — jede Aufnahme bleibt mit ihrem Ball verknüpft." },
      { q: "Kann ich ohne Empfang scoren?", a: "Das Scoring funktioniert auch bei schlechter Abdeckung weiter und synchronisiert sich, sobald die Verbindung zurück ist." },
      { q: "Werden Regenregeln unterstützt?", a: "Ja. CricLume wendet die üblichen Regenregeln an, um Ziele und Ergebnisse bei Unterbrechungen anzupassen." },
      { q: "Wo werden Videos gespeichert?", a: "Clips und Anmerkungen werden beim Spiel im eigenen Bereich deiner Organisation gespeichert; Einwilligungs- und Datenschutzkontrollen sind Teil der Roadmap." },
      { q: "Können andere Clubs und die Liga unser Scoring live sehen?", a: "Ja. Jedes Spiel hat eine Sichtbarkeitseinstellung: privat, mit dem Gegner geteilt, für die Liga offen oder als öffentlicher Link. Ligen können auch eine Voreinstellung für alle Spiele festlegen." },
      { q: "Wie verdient CricLume Geld?", a: "Clubs und Ligen zahlen ein Abo pro Team oder Wettbewerb, passend zum Umfang von Scoring, Video und Analyse. Zusätzlicher Videospeicher, Liga-Pakete und gesponserte Streams sind kostenpflichtige Add-ons." },
      { q: "Gibt es eine kostenlose Option?", a: "Ja. Starter ist kostenlos für ein Team mit Scoring Ball für Ball und Live-Anzeigetafel. Der Kameraraum ist nicht enthalten — Winkel gibt es ab dem Club-Tarif. Finanziert wird das über leichte Werbung." },
      { q: "Wie bekomme ich Zugang?", a: "Melde dich an, wenn dein Club bereits ein Konto hat, oder frage eine Einladung an — wir richten deinen Club ein." },
    ],
  },
  login: {
    badge: "Geschützter Zugang",
    title: "Anmelden",
    body: "Melde dich an, um die Scoring-Plattform zu öffnen, oder frage eine Einladung für deinen Club an.",
    email: "Club-E-Mail",
    password: "Passwort",
    submit: "Plattform öffnen",
    sent: "Danke — wir haben deine Anfrage erhalten und melden uns.",
    noAccount: "Noch kein Konto?",
    requestInvite: "Einladung für deinen Club anfragen.",
    copyright: "CricLume. Jeder Ball. Jeder Vorteil.",
  },
  footer: {
    desc: "Scoring Ball für Ball, Kameraräume mit mehreren Winkeln, Live-Anzeigetafeln und Trainingsanalyse für Clubs, Ligen und Akademien.",
    explore: "Entdecken",
    access: "Zugang",
    accessLine1: "Auf Einladung für Clubs",
    accessLine2: "Zugang für dein Team anfragen",
    cta: "Einladung anfragen",
    copyright: "CricLume — Jeder Ball. Jeder Vorteil.",
    legal: "CricLume ist ein Handelsname der iTechLounge Ltd.",
  },
  backToHome: "Zurück zum Start",
};

export const nl: Content = {
  langName: "Nederlands",
  nav: { home: "Home", features: "Functies", screens: "Schermen", pricing: "Prijzen", faq: "FAQ", login: "Inloggen" },
  ticker: [
    "Live • Riverside CC 148/4 (18.2)",
    "4+ camerahoeken per bal",
    "Coachingsanalyse • beeld voor beeld",
    "Vraag een uitnodiging aan voor je club",
    "Scoreborden klaar voor stream-overlay",
  ],
  hero: {
    l1: "Elke bal.",
    l2: "Elke hoek.",
    l3: "Elk voordeel.",
    body: "CricLume maakt van een clubwedstrijd een volledig verslag: scoren bal voor bal, gesynchroniseerde telefooncamera's vanuit elke hoek, live scoreborden en een analysekamer waar het hele team van leert.",
    ctaPrimary: "Inloggen bij CricLume",
    ctaSecondary: "Bekijk de schermen",
    liveNow: "Nu live",
  },
  stats: [
    { k: "4+", v: "camerahoeken per bal" },
    { k: "<1s", v: "om een bal vast te leggen" },
    { k: "100%", v: "wedstrijdhistorie bewaard" },
  ],
  home: {
    matchDayKicker: "Wedstrijddag",
    matchDayTitle: "Gebouwd voor de wedstrijddag",
    allFeatures: "Alle functies",
    fixturesKicker: "Programma",
    fixturesTitle: "Komende wedstrijden",
    scoring: "Scoren",
    vs: "tegen",
    seasonKicker: "Seizoen",
    seasonTitle: "Clubstand",
    standingsNote: "Standen, run rates en spelersstatistieken ontstaan automatisch uit elke bal die je scoort.",
    tablePos: "Pos",
    tableClub: "Club",
    tableP: "G",
    tableW: "W",
    tablePts: "Ptn",
    ctaKicker: "Analysekamer",
    ctaTitle1: "Kijk de wedstrijd terug,",
    ctaTitle2: "bal voor bal",
    ctaBody: "Elke bal is gekoppeld aan zijn eigen gesynchroniseerde hoeken — vertraag, stap door beelden, teken erop en stuur spraaknotities naar het team.",
    ctaButton: "Toegang krijgen",
    trustKicker: "Gebouwd met",
    trustTitle: "Clubs, competities en academies",
    tags: { league: "Competitie", academy: "Academie", cup: "T20-beker" },
  },
  features: [
    { title: "Snel scoren bal voor bal", body: "Runs, dots, wides, no-balls, byes, leg-byes, straffen en elk type dismissal — met ongedaan maken en tijdstempels op elke bal." },
    { title: "Camerakamer met meerdere telefoons", body: "Koppel telefoons aan beide kanten en van opzij — of voeg zoveel hoeken toe als nodig. Eén tik start de kamer en elke hoek blijft aan zijn bal gekoppeld." },
    { title: "Coachingsanalyse", body: "Slow motion, beeld-voor-beeld, hoeken wisselen, zoomen, tekengereedschap en spraaknotities voor feedback na de wedstrijd." },
    { title: "Live scoreborden", body: "Scoreborden van uitzendkwaliteit met run rate, partnerships, wicketverloop en een doorlopende baltijdlijn." },
    { title: "Desktop en mobiel", body: "Scoor met een telefoon langs de lijn of met een laptop in het clubhuis — dezelfde wedstrijd, synchroon." },
    { title: "Clubs, teams en spelers", body: "Organisaties, competities, teams, spelers en velden, van de grond af opgezet voor een heel seizoen." },
    { title: "Live scoren delen", body: "Competities en clubs bepalen wie een wedstrijd live volgt — de tegenstander, supporters, het competitiebureau of een openbare link." },
  ],
  featuresTab: {
    kicker: "Platform",
    title: "Functies",
    intro: "Alles wat in de huidige CricLume-build zit.",
    watchTitle: "Wie mag live meekijken",
    watchBody: "Competities stellen een standaard in, clubs kunnen die per wedstrijd aanpassen — zelfs tijdens een innings.",
    watchOptions: [
      { t: "Alleen club", d: "Scorers, coaches en leden van je eigen club." },
      { t: "Tegenstander", d: "Staf en spelers van het andere team volgen dezelfde live feed." },
      { t: "Competitiebureau", d: "Beheerders zien elke wedstrijd live voor uitslagen en naleving." },
      { t: "Openbare link", d: "Supporters en familie volgen het scorebord in een browser — geen account nodig." },
    ],
    alsoTitle: "Ook inbegrepen",
    alsoItems: [
      "Veldzones, fielderselectie en baltijdlijn",
      "Ongedaan maken op elke bal, met volledige wijzigingshistorie",
      "Spraaknotities en AI-analyse in de review",
      "Competities, innings en ballen per club opgeslagen",
      "Demowedstrijddata om te proberen vóór onboarding",
    ],
  },
  screensTab: {
    kicker: "Producttour",
    title: "Schermen",
    intro: "Dashboards, scoreborden, mobiel scoren en de analysekamer.",
    items: [
      { label: "Clubdashboard", caption: "Desktop • live, komende en afgeronde wedstrijden met run-rate- en wagon-wheel-analyses" },
      { label: "Live scorebord", caption: "Uitzendweergave • score, batters, bowlers, overtijdlijn en wicketverloop" },
      { label: "Mobiel scoren", caption: "Telefoon • scorepad voor de duim met extras, dismissals en recente ballen" },
      { label: "Coachingsanalyse", caption: "Desktop • vier gesynchroniseerde hoeken, beeld-voor-beeld scrubben en tekengereedschap" },
    ],
  },
  pricing: {
    kicker: "Abonnementen",
    title: "Prijzen & abonnementen",
    intro: "Begin gratis met één team. Stap over op een club- of competitieabonnement voor meer hoeken, langere videobewaring en controle over de hele competitie.",
    showing: "Prijzen voor",
    detecting: "Regio detecteren…",
    selectLabel: "Kies je land",
    mostPopular: "Meest gekozen",
    free: "Gratis",
    custom: "Op maat",
    plans: [
      {
        name: "Starter",
        period: "één team",
        blurb: "Laat één team goed scoren en deel een live scorebord.",
        perks: [
          "Bal voor bal scoren voor 1 team",
          "Live scorebord + openbare wedstrijdlink",
          "Geen camerakamer — upgrade voor hoeken",
          "Basisstatistieken batting & bowling",
          "Lichte advertenties op scorebord- en analysepagina's",
        ],
        cta: "Gratis beginnen",
      },
      {
        name: "Club",
        period: "per team / maand",
        blurb: "De volledige wedstrijduitrusting voor clubs met meerdere teams.",
        perks: [
          "Onbeperkt teams en wedstrijden",
          "Onbeperkt camerahoeken per bal",
          "90 dagen videobewaring + clipexport",
          "Analyse met slow-motion tagging",
          "Live scoren delen met tegenstanders",
          "Clubanalyses voor het hele seizoen",
        ],
        cta: "Uitnodiging aanvragen",
      },
      {
        name: "Competitie",
        period: "per competitie / seizoen",
        blurb: "Scoren, standen en beheer voor de hele competitie.",
        perks: [
          "Alle clubs in de competitie inbegrepen",
          "Standen, uitslagen en beheerconsole",
          "Standaard zichtbaarheidsregels voor alle wedstrijden",
          "12 maanden videobewaring",
          "Sponsorbranding op live streams",
          "Data-export en prioriteitssupport",
        ],
        cta: "Neem contact op",
      },
    ],
    revenueKicker: "Verdienmodel",
    revenueTitle: "Hoe CricLume geld verdient",
    revenue: [
      { title: "Abonnementen", body: "Terugkerende club- en competitieabonnementen vormen de kern — maandelijks of jaarlijks per team, met twee maanden gratis bij jaarbetaling." },
      { title: "Video- & opslagextra's", body: "Langere bewaring, 4K-clips en volledige seizoensarchieven worden bovenop het basistarief berekend." },
      { title: "Sponsoring & streams", body: "Competities kunnen gebrande overlays en gesponsorde wedstrijdlinks verkopen; CricLume krijgt een deel." },
      { title: "Diensten", body: "Onboarding, migratie van historische data en rapportage op maat voor grotere competities en academies." },
    ],
    footnote: "Jaarbetaling bespaart twee maanden op elk betaald abonnement. Scholen en jeugdafdelingen krijgen 50% korting op het Club-abonnement.",
  },
  faq: {
    kicker: "Antwoorden",
    title: "FAQ",
    items: [
      { q: "Voor wie is CricLume?", a: "Voor clubs, competities, scholen en academies die goede bal-voor-bal-data en video willen waarmee je echt kunt coachen — zonder uitzendbudget." },
      { q: "Heb ik speciale camera's nodig?", a: "Nee. De camerakamer koppelt gewone telefoons. Begin met één aan beide kanten en één van opzij en voeg zoveel hoeken toe als je wilt — elke opname blijft aan zijn bal gekoppeld." },
      { q: "Kan ik scoren zonder bereik?", a: "Scoren blijft werken bij slechte dekking en synchroniseert zodra de verbinding terug is." },
      { q: "Ondersteunt het regenregels?", a: "Ja. CricLume past standaard regenregels toe om doelen en uitslagen aan te passen bij onderbrekingen." },
      { q: "Waar wordt video opgeslagen?", a: "Clips en annotaties worden bij de wedstrijd opgeslagen in de eigen ruimte van je organisatie, met toestemmings- en privacycontroles op de roadmap." },
      { q: "Kunnen andere clubs en de competitie ons live volgen?", a: "Ja. Elke wedstrijd heeft een zichtbaarheidsinstelling: privé, gedeeld met de tegenstander, open voor de competitie of een openbare link. Competities kunnen ook een standaard instellen." },
      { q: "Hoe verdient CricLume geld?", a: "Clubs en competities betalen een abonnement per team of competitie, passend bij hoeveel scoren, video en analyse ze gebruiken. Extra opslag, competitiepakketten en gesponsorde streams zijn betaalde extra's." },
      { q: "Is er een gratis optie?", a: "Ja. Starter is gratis voor één team met bal-voor-bal scoren en een live scorebord. De camerakamer zit er niet bij — hoeken krijg je vanaf het Club-abonnement. Het wordt ondersteund door lichte advertenties." },
      { q: "Hoe krijg ik toegang?", a: "Log in als je club al een account heeft, of vraag een uitnodiging aan — dan zetten wij je club klaar." },
    ],
  },
  login: {
    badge: "Beveiligde toegang",
    title: "Inloggen",
    body: "Log in om het scoringsplatform te openen, of vraag een uitnodiging aan voor je club.",
    email: "Club-e-mail",
    password: "Wachtwoord",
    submit: "Ga naar het platform",
    sent: "Bedankt — we hebben je aanvraag genoteerd en nemen contact op.",
    noAccount: "Nog geen account?",
    requestInvite: "Vraag een uitnodiging aan voor je club.",
    copyright: "CricLume. Elke bal. Elk voordeel.",
  },
  footer: {
    desc: "Bal voor bal scoren, camerakamers met meerdere hoeken, live scoreborden en coachingsanalyse voor clubs, competities en academies.",
    explore: "Ontdek",
    access: "Toegang",
    accessLine1: "Op uitnodiging voor clubs",
    accessLine2: "Vraag toegang aan voor je team",
    cta: "Uitnodiging aanvragen",
    copyright: "CricLume — Elke bal. Elk voordeel.",
    legal: "CricLume is een handelsnaam van iTechLounge Ltd.",
  },
  backToHome: "Terug naar home",
};

export const af: Content = {
  langName: "Afrikaans",
  nav: { home: "Tuis", features: "Kenmerke", screens: "Skerms", pricing: "Pryse", faq: "Vrae", login: "Teken in" },
  ticker: [
    "Regstreeks • Riverside CC 148/4 (18.2)",
    "4+ kamerahoeke per bal",
    "Afrigtersontleding • raampie vir raampie",
    "Vra 'n uitnodiging vir jou klub aan",
    "Telborde gereed vir stroom-oorlegging",
  ],
  hero: {
    l1: "Elke bal.",
    l2: "Elke hoek.",
    l3: "Elke voordeel.",
    body: "CricLume maak van 'n klubwedstryd 'n volledige rekord: bal-vir-bal aantekening, gesinchroniseerde selfoonkameras uit elke hoek, regstreekse telborde en 'n ontledingskamer waaruit die hele span kan leer.",
    ctaPrimary: "Teken in by CricLume",
    ctaSecondary: "Sien die skerms",
    liveNow: "Nou regstreeks",
  },
  stats: [
    { k: "4+", v: "kamerahoeke per bal" },
    { k: "<1s", v: "om 'n bal aan te teken" },
    { k: "100%", v: "wedstrydgeskiedenis behou" },
  ],
  home: {
    matchDayKicker: "Wedstryddag",
    matchDayTitle: "Gebou vir wedstryddag",
    allFeatures: "Alle kenmerke",
    fixturesKicker: "Programme",
    fixturesTitle: "Komende wedstryde",
    scoring: "Aantekening",
    vs: "teen",
    seasonKicker: "Seisoen",
    seasonTitle: "Klubranglys",
    standingsNote: "Ranglyste, lopietempo's en spelerrekords bou hulself uit elke bal wat jy aanteken.",
    tablePos: "Pos",
    tableClub: "Klub",
    tableP: "G",
    tableW: "W",
    tablePts: "Pte",
    ctaKicker: "Ontledingskamer",
    ctaTitle1: "Kyk die wedstryd weer,",
    ctaTitle2: "bal vir bal",
    ctaBody: "Elke bal skakel na sy eie gesinchroniseerde hoeke — vertraag dit, stap deur raampies, teken daarop en stuur stemnotas aan die span.",
    ctaButton: "Kry toegang",
    trustKicker: "Gebou saam met",
    trustTitle: "Klubs, ligas en akademies",
    tags: { league: "Liga", academy: "Akademie", cup: "T20-beker" },
  },
  features: [
    { title: "Vinnige bal-vir-bal aantekening", body: "Lopies, dots, wides, no-balls, byes, leg-byes, strafpunte en elke uitboortipe — met ontdoen en tydstempels op elke bal." },
    { title: "Kamerakamer met verskeie fone", body: "Koppel fone aan albei kante en van die sykant — of voeg soveel hoeke by as wat nodig is. Een tik begin die kamer en elke hoek bly aan sy bal gekoppel." },
    { title: "Afrigtersontleding", body: "Stadige aksie, raampie-vir-raampie, hoekwisseling, zoem, tekengereedskap en stemnotas vir terugvoer ná die wedstryd." },
    { title: "Regstreekse telborde", body: "Uitsaaikwaliteit telborde met lopietempo, vennootskappe, paaltjieverlies en 'n rollende baltydlyn." },
    { title: "Rekenaar en selfoon", body: "Teken aan met 'n foon langs die kantlyn of 'n skootrekenaar in die klubhuis — dieselfde wedstryd, in sinchronisasie." },
    { title: "Klubs, spanne en spelers", body: "Organisasies, kompetisies, spanne, spelers en velde — van die grond af gebou vir 'n hele seisoen se geskiedenis." },
    { title: "Deel regstreekse aantekening", body: "Ligas en klubs kies wie 'n wedstryd regstreeks volg — die teenstander, ondersteuners, die ligakantoor, of 'n openbare skakel." },
  ],
  featuresTab: {
    kicker: "Platform",
    title: "Kenmerke",
    intro: "Alles wat in die huidige CricLume-weergawe beskikbaar is.",
    watchTitle: "Wie mag regstreeks kyk",
    watchBody: "Ligas stel 'n verstek vir 'n kompetisie; klubs kan dit per wedstryd verander — selfs tydens 'n beurt.",
    watchOptions: [
      { t: "Slegs klub", d: "Aantekenaars, afrigters en lede van jou eie klub." },
      { t: "Teenstanderklub", d: "Die ander span se personeel en spelers volg dieselfde regstreekse voer." },
      { t: "Ligakantoor", d: "Kompetisie-administrateurs sien elke wedstryd regstreeks vir uitslae en nakoming." },
      { t: "Openbare skakel", d: "Ondersteuners en familie volg die telbord in 'n blaaier — geen rekening nodig nie." },
    ],
    alsoTitle: "Ook ingesluit",
    alsoItems: [
      "Veldsones, veldwerkerkeuse en baltydlyn",
      "Ontdoen op enige bal, met volledige oudit van wysigings",
      "Stemnotas en KI-oudit in die ontleding",
      "Kompetisies, beurte en balle per klub gestoor",
      "Demo-wedstryddata om te toets voor aanboord",
    ],
  },
  screensTab: {
    kicker: "Produkttoer",
    title: "Skerms",
    intro: "Paneelborde, telborde, mobiele aantekening en die ontledingskamer.",
    items: [
      { label: "Klubpaneelbord", caption: "Rekenaar • regstreekse, komende en voltooide wedstryde met lopietempo- en wawiel-ontledings" },
      { label: "Regstreekse telbord", caption: "Uitsaai-aansig • telling, kolwers, bouliers, boulbeurt-tydlyn en paaltjieverlies" },
      { label: "Mobiele aantekening", caption: "Foon • duimvriendelike aantekenblad met ekstras, uitboorte en onlangse balle" },
      { label: "Afrigtersontleding", caption: "Rekenaar • vier gesinchroniseerde hoeke, raampie-vir-raampie navigasie en tekengereedskap" },
    ],
  },
  pricing: {
    kicker: "Planne",
    title: "Pryse en intekening",
    intro: "Begin gratis met een span. Gaan oor na 'n klub- of ligaplan wanneer jy meer hoeke, langer videoberging en kompetisiewye beheer wil hê.",
    showing: "Pryse vir",
    detecting: "Streek word bepaal…",
    selectLabel: "Kies jou land",
    mostPopular: "Gewildste",
    free: "Gratis",
    custom: "Pasgemaak",
    plans: [
      {
        name: "Starter",
        period: "een span",
        blurb: "Kry een span behoorlik aan die aanteken met 'n regstreekse telbord.",
        perks: [
          "Bal-vir-bal aantekening vir 1 span",
          "Regstreekse telbord + openbare wedstrydskakel",
          "Geen kamerakamer nie — opgradeer vir hoeke",
          "Basiese kolf- en boulstatistieke",
          "Ligte advertensies op telbord- en ontledingsbladsye",
        ],
        cta: "Begin gratis",
      },
      {
        name: "Klub",
        period: "per span / maand",
        blurb: "Die volle wedstryddagpakket vir klubs met verskeie spanne.",
        perks: [
          "Onbeperkte spanne en wedstryde",
          "Onbeperkte kamerahoeke per bal",
          "90 dae videoberging + knipsel-uitvoer",
          "Ontleding met stadige-aksie merking",
          "Deel regstreekse aantekening met teenstanders",
          "Klubontledings vir die hele seisoen",
        ],
        cta: "Vra 'n uitnodiging aan",
      },
      {
        name: "Liga",
        period: "per kompetisie / seisoen",
        blurb: "Kompetisiewye aantekening, ranglyste en bestuur.",
        perks: [
          "Elke klub in die kompetisie ingesluit",
          "Ligaranglyste, uitslae en admin-konsole",
          "Verstek sigbaarheidsreëls oor alle wedstryde",
          "12 maande videoberging",
          "Borgbemarking op regstreekse strome",
          "Data-uitvoer en voorkeurondersteuning",
        ],
        cta: "Praat met ons",
      },
    ],
    revenueKicker: "Sakemodel",
    revenueTitle: "Hoe CricLume geld maak",
    revenue: [
      { title: "Intekening", body: "Herhalende klub- en ligaplanne is die kern van die besigheid — maandeliks of jaarliks per span, met twee maande gratis op jaarlikse betaling." },
      { title: "Video- en bergingbyvoegings", body: "Langer berging, 4K-knipsels en volledige seisoenargiewe word bo-op die basisplan gehef." },
      { title: "Borgskap en strome", body: "Ligas kan gemerkte oorlegings en geborgde wedstrydskakels verkoop; CricLume kry 'n deel." },
      { title: "Dienste", body: "Aanboord, migrasie van historiese data en pasgemaakte verslae vir groter ligas en akademies." },
    ],
    footnote: "Jaarlikse betaling spaar twee maande op elke betaalde plan. Skole en juniorafdelings kry 50% afslag op die Klub-plan.",
  },
  faq: {
    kicker: "Antwoorde",
    title: "Vrae",
    items: [
      { q: "Vir wie is CricLume?", a: "Vir klubs, ligas, skole en akademies wat behoorlike bal-vir-bal rekords en video wil hê waarmee jy werklik kan afrig — sonder 'n uitsaaibegroting." },
      { q: "Het ek spesiale kameras nodig?", a: "Nee. Die kamerakamer koppel gewone fone. Begin met een aan elke kant en een van die sykant, en voeg soveel hoeke by as wat jy wil — elke opname bly aan sy bal gekoppel." },
      { q: "Kan ek sonder sein aanteken?", a: "Aantekening werk aan deur swak dekking en sinchroniseer weer sodra die verbinding terug is." },
      { q: "Hanteer dit reënreëls?", a: "Ja. CricLume pas standaard reënreëls toe om teikens en uitslae aan te pas wanneer 'n wedstryd onderbreek word." },
      { q: "Waar word video gestoor?", a: "Knipsels en aantekeninge word by die wedstryd in jou organisasie se eie ruimte gestoor, met toestemmings- en privaatheidskontroles op die padkaart." },
      { q: "Kan ander klubs en die liga ons regstreeks volg?", a: "Ja. Elke wedstryd het 'n sigbaarheidsinstelling: privaat, gedeel met die teenstander, oop vir die liga, of 'n openbare skakel. Ligas kan ook 'n verstek vir elke wedstryd stel." },
      { q: "Hoe maak CricLume geld?", a: "Klubs en ligas betaal 'n intekening per span of kompetisie, op die vlak wat pas by hoeveel aantekening, video en ontleding hulle gebruik. Ekstra berging, ligapakkette en geborgde strome is betaalde byvoegings." },
      { q: "Is daar 'n gratis opsie?", a: "Ja. Starter is gratis vir een span met bal-vir-bal aantekening en 'n regstreekse telbord. Die kamerakamer is nie ingesluit nie — hoeke kom by die Klub-plan. Dit word deur ligte advertensies ondersteun." },
      { q: "Hoe kry ek toegang?", a: "Teken in as jou klub reeds 'n rekening het, of vra 'n uitnodiging aan en ons sal jou klub opstel." },
    ],
  },
  login: {
    badge: "Beheerde toegang",
    title: "Teken in",
    body: "Teken in om die aantekenplatform te open, of vra 'n uitnodiging aan vir jou klub.",
    email: "Klub-e-pos",
    password: "Wagwoord",
    submit: "Gaan na die platform",
    sent: "Dankie — ons het jou versoek aangeteken en sal in kontak wees.",
    noAccount: "Nog geen rekening nie?",
    requestInvite: "Vra 'n uitnodiging aan vir jou klub.",
    copyright: "CricLume. Elke bal. Elke voordeel.",
  },
  footer: {
    desc: "Bal-vir-bal aantekening, kamerakamers met verskeie hoeke, regstreekse telborde en afrigtersontleding vir klubs, ligas en akademies.",
    explore: "Verken",
    access: "Toegang",
    accessLine1: "Op uitnodiging vir klubs",
    accessLine2: "Vra toegang aan vir jou span",
    cta: "Vra 'n uitnodiging aan",
    copyright: "CricLume — Elke bal. Elke voordeel.",
    legal: "CricLume is 'n handelsnaam van iTechLounge Ltd.",
  },
  backToHome: "Terug na tuis",
};

export const fr: Content = {
  langName: "Français",
  nav: { home: "Accueil", features: "Fonctions", screens: "Écrans", pricing: "Tarifs", faq: "FAQ", login: "Connexion" },
  ticker: [
    "En direct • Riverside CC 148/4 (18.2)",
    "4+ angles de caméra par balle",
    "Analyse d'entraînement • image par image",
    "Demandez une invitation pour votre club",
    "Tableaux de score prêts pour l'overlay de stream",
  ],
  hero: {
    l1: "Chaque balle.",
    l2: "Chaque angle.",
    l3: "Chaque avantage.",
    body: "CricLume transforme un match de club en archive complète : marquage balle par balle, caméras de téléphone synchronisées sous tous les angles, tableaux de score en direct et une salle d'analyse dont toute l'équipe profite.",
    ctaPrimary: "Se connecter à CricLume",
    ctaSecondary: "Voir les écrans",
    liveNow: "En direct",
  },
  stats: [
    { k: "4+", v: "angles de caméra par balle" },
    { k: "<1s", v: "pour enregistrer une balle" },
    { k: "100%", v: "historique des matchs conservé" },
  ],
  home: {
    matchDayKicker: "Jour de match",
    matchDayTitle: "Conçu pour le jour de match",
    allFeatures: "Toutes les fonctions",
    fixturesKicker: "Calendrier",
    fixturesTitle: "Prochains matchs",
    scoring: "Marquage",
    vs: "contre",
    seasonKicker: "Saison",
    seasonTitle: "Classement des clubs",
    standingsNote: "Classements, run rates et statistiques des joueurs se construisent à partir de chaque balle enregistrée.",
    tablePos: "Pos",
    tableClub: "Club",
    tableP: "J",
    tableW: "V",
    tablePts: "Pts",
    ctaKicker: "Salle d'analyse",
    ctaTitle1: "Revoyez le match,",
    ctaTitle2: "balle par balle",
    ctaBody: "Chaque balle est liée à ses angles synchronisés — ralentissez, avancez image par image, dessinez dessus et envoyez des notes vocales à l'équipe.",
    ctaButton: "Obtenir l'accès",
    trustKicker: "Construit avec",
    trustTitle: "Clubs, ligues et académies",
    tags: { league: "Ligue", academy: "Académie", cup: "Coupe T20" },
  },
  features: [
    { title: "Marquage rapide balle par balle", body: "Runs, dots, wides, no-balls, byes, leg-byes, pénalités et tous les types d'élimination — avec annulation et horodatage sur chaque balle." },
    { title: "Salle caméra multi-téléphones", body: "Associez des téléphones aux deux extrémités et de côté — ou ajoutez autant d'angles que nécessaire. Un appui lance la salle et chaque angle reste lié à sa balle." },
    { title: "Analyse d'entraînement", body: "Ralenti, image par image, changement d'angle, zoom, outils de dessin et notes vocales pour le retour d'après-match." },
    { title: "Tableaux de score en direct", body: "Tableaux de qualité broadcast avec run rate, partenariats, chute des guichets et chronologie des balles." },
    { title: "Ordinateur et mobile", body: "Marquez depuis un téléphone au bord du terrain ou un portable au club — le même match, synchronisé." },
    { title: "Clubs, équipes et joueurs", body: "Organisations, compétitions, équipes, joueurs et terrains modélisés pour toute une saison." },
    { title: "Partager le direct", body: "Ligues et clubs choisissent qui suit un match en temps réel — le club adverse, les supporters, la ligue ou un lien public." },
  ],
  featuresTab: {
    kicker: "Plateforme",
    title: "Fonctions",
    intro: "Tout ce que contient la version actuelle de CricLume.",
    watchTitle: "Qui peut regarder en direct",
    watchBody: "Les ligues définissent une valeur par défaut, les clubs peuvent la modifier match par match — même en cours de manche.",
    watchOptions: [
      { t: "Club uniquement", d: "Marqueurs, entraîneurs et membres de votre club." },
      { t: "Club adverse", d: "Le staff et les joueurs adverses suivent le même flux en direct." },
      { t: "Bureau de la ligue", d: "Les administrateurs voient chaque match en direct pour les résultats et la conformité." },
      { t: "Lien public", d: "Supporters et familles suivent le tableau dans un navigateur — sans compte." },
    ],
    alsoTitle: "Également inclus",
    alsoItems: [
      "Zones de champ, sélection des fielders et chronologie des balles",
      "Annulation sur chaque balle, avec historique complet des modifications",
      "Notes vocales et analyse IA dans la revue",
      "Compétitions, manches et balles enregistrées par club",
      "Données de match de démo pour tester avant l'intégration",
    ],
  },
  screensTab: {
    kicker: "Visite du produit",
    title: "Écrans",
    intro: "Tableaux de bord, tableaux de score, marquage mobile et salle d'analyse.",
    items: [
      { label: "Tableau de bord du club", caption: "Bureau • matchs en direct, à venir et terminés avec analyses de run rate et wagon wheel" },
      { label: "Tableau de score en direct", caption: "Vue broadcast • score, batteurs, lanceurs, chronologie des overs et chute des guichets" },
      { label: "Marquage mobile", caption: "Téléphone • pavé de marquage au pouce avec extras, éliminations et balles récentes" },
      { label: "Analyse d'entraînement", caption: "Bureau • quatre angles synchronisés, navigation image par image et outils de dessin" },
    ],
  },
  pricing: {
    kicker: "Formules",
    title: "Tarifs et abonnements",
    intro: "Commencez gratuitement avec une équipe. Passez à un abonnement club ou ligue pour plus d'angles, une conservation vidéo plus longue et un contrôle sur toute la compétition.",
    showing: "Tarifs pour",
    detecting: "Détection de votre région…",
    selectLabel: "Choisissez votre pays",
    mostPopular: "Le plus choisi",
    free: "Gratuit",
    custom: "Sur mesure",
    plans: [
      {
        name: "Starter",
        period: "une équipe",
        blurb: "Faites marquer correctement une équipe et partagez un tableau en direct.",
        perks: [
          "Marquage balle par balle pour 1 équipe",
          "Tableau de score en direct + lien public",
          "Pas de salle caméra — passez à l'offre supérieure",
          "Statistiques de base batting et bowling",
          "Publicité légère sur les pages score et analyse",
        ],
        cta: "Commencer gratuitement",
      },
      {
        name: "Club",
        period: "par équipe / mois",
        blurb: "L'équipement complet du jour de match pour les clubs à plusieurs équipes.",
        perks: [
          "Équipes et matchs illimités",
          "Angles de caméra illimités par balle",
          "90 jours de conservation vidéo + export de clips",
          "Analyse avec marquage au ralenti",
          "Partage du direct avec les clubs adverses",
          "Analyses du club sur toute la saison",
        ],
        cta: "Demander une invitation",
      },
      {
        name: "Ligue",
        period: "par compétition / saison",
        blurb: "Marquage, classements et gouvernance pour toute la compétition.",
        perks: [
          "Tous les clubs de la compétition inclus",
          "Classements, résultats et console d'administration",
          "Règles de visibilité par défaut sur tous les matchs",
          "12 mois de conservation vidéo",
          "Marque du sponsor sur les diffusions",
          "Export des données et support prioritaire",
        ],
        cta: "Nous contacter",
      },
    ],
    revenueKicker: "Modèle économique",
    revenueTitle: "Comment CricLume gagne de l'argent",
    revenue: [
      { title: "Abonnements", body: "Les abonnements récurrents des clubs et ligues sont le cœur du modèle — mensuels ou annuels par équipe, avec deux mois offerts à l'année." },
      { title: "Options vidéo et stockage", body: "Conservation prolongée, clips 4K et archives de saison sont facturés en plus de la formule de base." },
      { title: "Sponsoring et diffusions", body: "Les ligues peuvent vendre des overlays sponsorisés et des liens de match parrainés ; CricLume perçoit une part." },
      { title: "Services", body: "Intégration, migration des données historiques et rapports sur mesure pour les grandes ligues et académies." },
    ],
    footnote: "Le paiement annuel offre deux mois sur chaque formule payante. Écoles et sections jeunes bénéficient de 50 % de remise sur la formule Club.",
  },
  faq: {
    kicker: "Réponses",
    title: "FAQ",
    items: [
      { q: "À qui s'adresse CricLume ?", a: "Aux clubs, ligues, écoles et académies qui veulent de vraies données balle par balle et des vidéos exploitables à l'entraînement — sans budget broadcast." },
      { q: "Faut-il des caméras spéciales ?", a: "Non. La salle caméra associe des téléphones ordinaires. Commencez avec un à chaque extrémité et un de côté, puis ajoutez autant d'angles que nécessaire — chaque enregistrement reste lié à sa balle." },
      { q: "Puis-je marquer sans réseau ?", a: "Le marquage continue de fonctionner avec une couverture faible et se synchronise dès le retour de la connexion." },
      { q: "Les règles de pluie sont-elles gérées ?", a: "Oui. CricLume applique les règles de pluie standard pour ajuster objectifs et résultats en cas d'interruption." },
      { q: "Où sont stockées les vidéos ?", a: "Clips et annotations sont stockés avec le match dans l'espace propre à votre organisation ; les contrôles de consentement et de confidentialité sont à la feuille de route." },
      { q: "Les autres clubs et la ligue peuvent-ils suivre en direct ?", a: "Oui. Chaque match a un réglage de visibilité : privé, partagé avec l'adversaire, ouvert à la ligue, ou lien public. Les ligues peuvent aussi définir une valeur par défaut." },
      { q: "Comment CricLume gagne-t-il de l'argent ?", a: "Clubs et ligues paient un abonnement par équipe ou compétition, selon leur usage du marquage, de la vidéo et de l'analyse. Stockage supplémentaire, packs de ligue et diffusions sponsorisées sont des options payantes." },
      { q: "Existe-t-il une offre gratuite ?", a: "Oui. Starter est gratuit pour une équipe avec marquage balle par balle et tableau en direct. La salle caméra n'est pas incluse — les angles arrivent avec la formule Club. Elle est financée par une publicité légère." },
      { q: "Comment obtenir un accès ?", a: "Connectez-vous si votre club a déjà un compte, ou demandez une invitation et nous préparerons votre club." },
    ],
  },
  login: {
    badge: "Accès réservé",
    title: "Connexion",
    body: "Connectez-vous pour ouvrir la plateforme de marquage, ou demandez une invitation pour votre club.",
    email: "E-mail du club",
    password: "Mot de passe",
    submit: "Accéder à la plateforme",
    sent: "Merci — nous avons enregistré votre demande et vous recontacterons.",
    noAccount: "Pas encore de compte ?",
    requestInvite: "Demandez une invitation pour votre club.",
    copyright: "CricLume. Chaque balle. Chaque avantage.",
  },
  footer: {
    desc: "Marquage balle par balle, salles caméra multi-angles, tableaux de score en direct et analyse d'entraînement pour clubs, ligues et académies.",
    explore: "Explorer",
    access: "Accès",
    accessLine1: "Sur invitation pour les clubs",
    accessLine2: "Demandez un accès pour votre équipe",
    cta: "Demander une invitation",
    copyright: "CricLume — Chaque balle. Chaque avantage.",
    legal: "CricLume est un nom commercial d'iTechLounge Ltd.",
  },
  backToHome: "Retour à l'accueil",
};

export const languages = { en, de, nl, af, fr } as const;
export type Lang = keyof typeof languages;
export const langOrder: Lang[] = ["en", "de", "nl", "af", "fr"];
